### ISSUE TITLE
Issue found when attempting to run

### ISSUE THREAD

**Issue by wschmrdrNS** [countergram/pytidylib#17]
>>> import tidylib
>>> tidylib.tidy_fragment('<root>asdf</root>', dict(input_xml=True))[0]
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/tidylib/tidy.py", line 227, in tidy_fragment
return get_module_tidy().tidy_fragment(text, options)
File "/usr/local/lib/python2.7/dist-packages/tidylib/tidy.py", line 233, in get_module_tidy
_tidy = Tidy()
File "/usr/local/lib/python2.7/dist-packages/tidylib/tidy.py", line 95, in init
if self._tidy is None:
AttributeError: 'Tidy' object has no attribute '_tidy'

Found after attempting to pip install pytidylib and running it through a python prompt. Evidently some steps are missing in the installation process, or the global declaration isn't proper. I am running Python 2.7.6.

**Comment by wschmrdrNS** [comment]
Missed an install step. :(
